services:
  backend:
    build:
      context: ./backend
      target: dev
    volumes:
      - ./backend/src:/app/src
      - ./backend/config:/app/config
      - ./backend/migrations:/app/migrations

  frontend:
    build:
      context: ./frontend
      target: dev
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
    environment:
      WATCHPACK_POLLING: "true"
