export { MailboxLayout, type MailboxLayoutProps } from './MailboxLayout'
export { MailboxHeader, type MailboxHeaderProps } from './MailboxHeader'
export { MailboxSidebar, type MailboxSidebarProps } from './MailboxSidebar'
export { EmailDetail, type EmailDetailProps, type EmailDetailEmail } from './EmailDetail'
export { ComposerLayout, type ComposerLayoutProps } from './ComposerLayout'
export { SettingsLayout, type SettingsLayoutProps, type SettingsSection } from './SettingsLayout'
