{{- if .Values.backend.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nextra.fullname" . }}-backend
  labels:
    {{- include "nextra.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      {{- include "nextra.selectorLabels" (dict "ctx" . "component" "backend") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "nextra.selectorLabels" (dict "ctx" . "component" "backend") | nindent 8 }}
    spec:
      containers:
        - name: backend
          image: {{ include "nextra.image" (dict "ctx" . "image" .Values.backend.image) }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.backend.port }}
          env:
            - name: DB_HOST
              value: {{ include "nextra.fullname" . }}-postgres
            - name: DB_PORT
              value: {{ .Values.postgres.port | quote }}
            - name: DB_NAME
              value: {{ .Values.postgres.database | quote }}
            - name: DB_USER
              value: {{ .Values.postgres.user | quote }}
            - name: REDIS_HOST
              value: {{ include "nextra.fullname" . }}-redis
            - name: KAFKA_BROKERS
              value: {{ include "nextra.fullname" . }}-kafka:{{ .Values.kafka.port }}
          readinessProbe:
            httpGet: { path: /healthz, port: http }
            initialDelaySeconds: 5
          livenessProbe:
            httpGet: { path: /healthz, port: http }
            initialDelaySeconds: 15
          resources:
            {{- toYaml .Values.backend.resources | nindent 12 }}
{{- end -}}
