{{- if .Values.elasticsearch.enabled -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "nextra.fullname" . }}-elasticsearch
  labels:
    {{- include "nextra.labels" . | nindent 4 }}
    app.kubernetes.io/component: elasticsearch
spec:
  serviceName: {{ include "nextra.fullname" . }}-elasticsearch
  replicas: 1
  selector:
    matchLabels:
      {{- include "nextra.selectorLabels" (dict "ctx" . "component" "elasticsearch") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "nextra.selectorLabels" (dict "ctx" . "component" "elasticsearch") | nindent 8 }}
    spec:
      containers:
        - name: elasticsearch
          image: {{ .Values.elasticsearch.image }}
          ports:
            - name: http
              containerPort: {{ .Values.elasticsearch.port }}
          env:
            - name: discovery.type
              value: single-node
            - name: xpack.security.enabled
              value: "false"
            - name: ES_JAVA_OPTS
              value: "-Xms512m -Xmx512m"
          volumeMounts:
            - name: data
              mountPath: /usr/share/elasticsearch/data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.elasticsearch.storage }}
{{- end -}}
