{{- if .Values.frontend.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nextra.fullname" . }}-frontend
  labels:
    {{- include "nextra.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      {{- include "nextra.selectorLabels" (dict "ctx" . "component" "frontend") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "nextra.selectorLabels" (dict "ctx" . "component" "frontend") | nindent 8 }}
    spec:
      containers:
        - name: frontend
          image: {{ include "nextra.image" (dict "ctx" . "image" .Values.frontend.image) }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.frontend.port }}
          env:
            - name: NEXT_PUBLIC_API_URL
              value: "http://{{ include "nextra.fullname" . }}-backend:{{ .Values.backend.port }}"
            - name: PORT
              value: {{ .Values.frontend.port | quote }}
          readinessProbe:
            httpGet: { path: /, port: http }
            initialDelaySeconds: 10
          livenessProbe:
            httpGet: { path: /, port: http }
            initialDelaySeconds: 30
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
{{- end -}}
