{{- if .Values.portal.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nextra.fullname" . }}-portal
  labels:
    {{- include "nextra.labels" . | nindent 4 }}
    app.kubernetes.io/component: portal
spec:
  replicas: {{ .Values.portal.replicas }}
  selector:
    matchLabels:
      {{- include "nextra.selectorLabels" (dict "ctx" . "component" "portal") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "nextra.selectorLabels" (dict "ctx" . "component" "portal") | nindent 8 }}
    spec:
      containers:
        - name: portal
          image: "{{ .Values.portal.image }}:{{ .Values.portal.imageTag }}"
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.portal.port }}
          volumeMounts:
            - name: nginx-conf
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
      volumes:
        - name: nginx-conf
          configMap:
            name: {{ include "nextra.fullname" . }}-nginx
{{- end -}}
