{{- if .Values.postgres.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nextra.fullname" . }}-postgres
  labels:
    {{- include "nextra.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
type: Opaque
stringData:
  password: {{ .Values.postgres.password | default (randAlphaNum 24) | quote }}
{{- end -}}
