{{- if .Values.sso.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "nextra.fullname" . }}-sso
  labels:
    {{- include "nextra.labels" . | nindent 4 }}
    app.kubernetes.io/component: sso
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.sso.port }}
      targetPort: http
  selector:
    {{- include "nextra.selectorLabels" (dict "ctx" . "component" "sso") | nindent 4 }}
{{- end -}}
