/**
 * Navigation component re-exports.
 */
export {
  Breadcrumbs,
  type BreadcrumbsProps,
  type BreadcrumbItem,
  Link,
  type LinkProps,
  Menu,
  MenuItem,
  MenuList,
  type MenuProps,
  type MenuItemProps,
  type MenuListProps,
  Pagination,
  PaginationItem,
  type PaginationProps,
  Stepper,
  Step,
  StepLabel,
  StepButton,
  StepContent,
  StepConnector,
  StepIcon,
  Tabs,
  Tab,
  TabPanel,
  type TabsProps,
  type TabProps,
  type TabPanelProps,
  BottomNavigation,
  BottomNavigationAction,
  SpeedDial,
  SpeedDialAction,
  SpeedDialIcon,
  ProjectSidebar,
  type ProjectSidebarProps,
  type ProjectSidebarItem,
  type ProjectSidebarWorkspace,
} from '../navigation';
